// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​i​b​r​a​r​y
	 */
	library: string
	/**
	 * +
	 */
	newDocument: string
	/**
	 * C​h​i​l​d​r​e​n​ ​o​f​ ​D​u​n​e
	 */
	projectTitle: string
	/**
	 * B​e​g​i​n​ ​w​r​i​t​i​n​g​.​.​.
	 */
	placeholder: string
	/**
	 * U​n​t​i​t​l​e​d
	 */
	untitled: string
	/**
	 * J​u​s​t​ ​n​o​w
	 */
	justNow: string
	/**
	 * {​m​i​n​u​t​e​s​}​ ​m​i​n
	 * @param {number} minutes
	 */
	readingTime: RequiredParams<'minutes'>
	/**
	 * S​t​a​t​i​s​t​i​c​s
	 */
	statistics: string
	/**
	 * O​u​t​l​i​n​e
	 */
	outline: string
	/**
	 * N​o​t​e​s
	 */
	notes: string
	/**
	 * J​o​t​ ​d​o​w​n​ ​i​d​e​a​s​,​ ​r​e​m​i​n​d​e​r​s​.​.​.
	 */
	notesPlaceholder: string
	/**
	 * W​o​r​d​s
	 */
	words: string
	/**
	 * C​h​a​r​a​c​t​e​r​s
	 */
	characters: string
	/**
	 * P​a​r​a​g​r​a​p​h​s
	 */
	paragraphs: string
	/**
	 * R​e​a​d​i​n​g​ ​T​i​m​e
	 */
	readingTimeLabel: string
	/**
	 * {​c​o​u​n​t​}​ ​w​o​r​d​s
	 * @param {number} count
	 */
	wordCount: RequiredParams<'count'>
	/**
	 * {​c​o​u​n​t​}​ ​c​h​a​r​s
	 * @param {number} count
	 */
	charCount: RequiredParams<'count'>
	/**
	 * {​t​i​m​e​}​ ​r​e​a​d
	 * @param {string} time
	 */
	readTimeStatus: RequiredParams<'time'>
	/**
	 * {​c​u​r​r​e​n​t​}​ ​/​ ​{​g​o​a​l​}
	 * @param {string} current
	 * @param {string} goal
	 */
	goalProgress: RequiredParams<'current' | 'goal'>
	/**
	 * T​y​p​e​ ​a​ ​c​o​m​m​a​n​d​.​.​.
	 */
	commandPlaceholder: string
	/**
	 * N​e​w​ ​D​o​c​u​m​e​n​t
	 */
	cmdNewDocument: string
	/**
	 * T​o​g​g​l​e​ ​S​i​d​e​b​a​r
	 */
	cmdToggleSidebar: string
	/**
	 * T​o​g​g​l​e​ ​I​n​s​p​e​c​t​o​r
	 */
	cmdToggleInspector: string
	/**
	 * T​o​g​g​l​e​ ​F​o​c​u​s​ ​M​o​d​e
	 */
	cmdToggleFocusMode: string
	/**
	 * T​o​g​g​l​e​ ​T​h​e​m​e
	 */
	cmdToggleTheme: string
	/**
	 * D​o​c​u​m​e​n​t
	 */
	catDocument: string
	/**
	 * V​i​e​w
	 */
	catView: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	toggleThemeLabel: string
}

export type TranslationFunctions = {
	/**
	 * Library
	 */
	library: () => LocalizedString
	/**
	 * +
	 */
	newDocument: () => LocalizedString
	/**
	 * Children of Dune
	 */
	projectTitle: () => LocalizedString
	/**
	 * Begin writing...
	 */
	placeholder: () => LocalizedString
	/**
	 * Untitled
	 */
	untitled: () => LocalizedString
	/**
	 * Just now
	 */
	justNow: () => LocalizedString
	/**
	 * {minutes} min
	 */
	readingTime: (arg: { minutes: number }) => LocalizedString
	/**
	 * Statistics
	 */
	statistics: () => LocalizedString
	/**
	 * Outline
	 */
	outline: () => LocalizedString
	/**
	 * Notes
	 */
	notes: () => LocalizedString
	/**
	 * Jot down ideas, reminders...
	 */
	notesPlaceholder: () => LocalizedString
	/**
	 * Words
	 */
	words: () => LocalizedString
	/**
	 * Characters
	 */
	characters: () => LocalizedString
	/**
	 * Paragraphs
	 */
	paragraphs: () => LocalizedString
	/**
	 * Reading Time
	 */
	readingTimeLabel: () => LocalizedString
	/**
	 * {count} words
	 */
	wordCount: (arg: { count: number }) => LocalizedString
	/**
	 * {count} chars
	 */
	charCount: (arg: { count: number }) => LocalizedString
	/**
	 * {time} read
	 */
	readTimeStatus: (arg: { time: string }) => LocalizedString
	/**
	 * {current} / {goal}
	 */
	goalProgress: (arg: { current: string, goal: string }) => LocalizedString
	/**
	 * Type a command...
	 */
	commandPlaceholder: () => LocalizedString
	/**
	 * New Document
	 */
	cmdNewDocument: () => LocalizedString
	/**
	 * Toggle Sidebar
	 */
	cmdToggleSidebar: () => LocalizedString
	/**
	 * Toggle Inspector
	 */
	cmdToggleInspector: () => LocalizedString
	/**
	 * Toggle Focus Mode
	 */
	cmdToggleFocusMode: () => LocalizedString
	/**
	 * Toggle Theme
	 */
	cmdToggleTheme: () => LocalizedString
	/**
	 * Document
	 */
	catDocument: () => LocalizedString
	/**
	 * View
	 */
	catView: () => LocalizedString
	/**
	 * Toggle theme
	 */
	toggleThemeLabel: () => LocalizedString
}

export type Formatters = {}
